name: 'Publish to Snap'
description: 'Publish the Linux package to Snap'
inputs:
  release-version:
    description: 'The release version'
    required: true
  artifact-name:
    description: 'The name of the artifact zip file'
    required: true
  release-tag:
    description: 'The release tag'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Unzip
      run: |
        mkdir -p artifacts
        tar -xzvf ${{ inputs.artifact-name }} -C artifacts
      shell: bash

    - name: Generate snapcraft.yaml
      run: |
        chmod +x ./scripts/snap/create-snapcraft-yaml.sh
        ./scripts/snap/create-snapcraft-yaml.sh ${{ github.workspace }} ${{ inputs.release-version }} "stable" "artifacts"
      shell: bash

    - name: Build snap
      uses: snapcore/action-build@v1
      with:
        snapcraft-args: --target-arch amd64

    - name: Append the snap file to release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: |
          *.snap
        tag_name: ${{ inputs.release-tag }}
        prerelease: ${{ contains(inputs.release-tag, 'beta') }}

    # once we have the release token, we will publish the snap to Snap Store
    # - name: Set path to snap binary
    #   shell: bash
    #   run: |
    #     echo "SNAP_BINARY_PATH=$(find ${{ github.workspace }} -name '*.snap')" >> $GITHUB_ENV

    # - name: Publish snap
    #   uses: snapcore/action-publish@v1
    #   env:
    #     SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_RELEASE_TOKEN }}
    #   with:
    #     snap: ${{ env.SNAP_BINARY_PATH }}
    #     release: stable
